# -*- coding: utf-8 -*-
"""TSDS MobileNetV2.ipynb

Automatically generated by Colab.



#mount google drive
from google.colab import drive
drive.mount('/content/drive')

"""# New section"""

#deine paths
train_dir = "/content/drive/MyDrive/Traditional Attire detection system/dataset/train"
validation_dir = "/content/drive/MyDrive/Traditional Attire detection system/dataset/val"
test_dir = "/content/drive/MyDrive/Traditional Attire detection system/dataset/test"

#import dataset
import tensorflow as tf

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True
)

validation_ds = tf.keras.utils.image_dataset_from_directory(
    validation_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

#check class names
print(train_ds.class_names)
print(validation_ds.class_names)
print(test_ds.class_names)

#normalise the images
normalization_layer = tf.keras.layers.Rescaling(1./255)

train_ds = train_ds.map(lambda x, y: (normalization_layer(x), y))
validation_ds = validation_ds.map(lambda x, y: (normalization_layer(x), y))
test_ds = test_ds.map(lambda x, y: (normalization_layer(x), y))

#create augmentation pipeline
data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.15),
    tf.keras.layers.RandomZoom(0.15),
    tf.keras.layers.RandomTranslation(0.10, 0.10),
    tf.keras.layers.RandomContrast(0.10),
])

#apply augmentation to the training set only

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.map(
    lambda x, y: (data_augmentation(x, training=True), y),
    num_parallel_calls=AUTOTUNE
)

train_ds = train_ds.prefetch(AUTOTUNE)
validation_ds = validation_ds.prefetch(AUTOTUNE)
test_ds = test_ds.prefetch(AUTOTUNE)

#augmentation only to training 2
data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.15),
    tf.keras.layers.RandomZoom(0.15),
    tf.keras.layers.RandomTranslation(0.10, 0.10),
    tf.keras.layers.RandomContrast(0.10)
])

layers.Dropout(0.3)

#verify augmentation
import matplotlib.pyplot as plt

for images, labels in train_ds.take(1):
    plt.figure(figsize=(10,10))
    for i in range(9):
        ax = plt.subplot(3,3,i+1)
        plt.imshow(images[i].numpy())
        plt.axis("off")

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

#load pretrained moblieNetV2
base_model = MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)

#Do not change the weights of MobileNetV2 during training. The model keeps all the knowledge it learned from ImageNet.
base_model.trainable = False

#Build your classifier
#Assuming you currently have 5 tribes, change the last layer if the number of classes changes later.
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3), #reduces overfitting
    layers.Dense(128, activation='relu'), #connected layer which has 128 neurons (can increase to 256,512,..). It learns combinations. e.g. red stripe, diamond pattern, etc.. (without activation func relu it cannot learn complex pattern)
    layers.Dropout(0.3),
    layers.Dense(5, activation='softmax')   # Change to 17 later
])

#compile the model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

#train the model
history = model.fit(
    train_ds,
    validation_data=validation_ds,
    epochs=20
)

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    train_ds,
    validation_data=validation_ds,
    epochs=20,
    callbacks=[early_stop]
)

test_loss, test_accuracy = model.evaluate(test_ds)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

#training graph
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Training vs Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Training vs Validation Loss')

plt.show()

#precision
import numpy as np
from sklearn.metrics import classification_report

y_true = []
y_pred = []

for images, labels in test_ds:
    predictions = model.predict(images, verbose=0)

    predicted_classes = np.argmax(predictions, axis=1)

    y_true.extend(labels.numpy())
    y_pred.extend(predicted_classes)

y_true = np.array(y_true)
y_pred = np.array(y_pred)

class_names = test_ds.class_names = [
    'Angami',
    'Ao',
    'Konyak',
    'Lotha',
    'Sumi'
]

print(class_names)

#generate precision, recall and f1 score
report = classification_report(
    y_true,
    y_pred,
    target_names=class_names
)

print(report)

#confision matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

print(cm)

#display confusion matrix as a graph
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted Tribe")
plt.ylabel("Actual Tribe")
plt.title("MobileNetV2 Confusion Matrix")

plt.show()

#check training results
print("Training accuracy:", history.history['accuracy'][-1])
print("Validation accuracy:", history.history['val_accuracy'][-1])

print("Best validation accuracy:",
      max(history.history['val_accuracy']))

print("Best epoch:",
      np.argmax(history.history['val_accuracy']) + 1)

test_loss, test_accuracy = model.evaluate(test_ds)

print(f"Test Accuracy: {test_accuracy:.4f}")

model.save("/content/drive/MyDrive/MobileNetV2_NagaShawl.keras")

#upload image
from google.colab import files

uploaded = files.upload()

#load the uploaded image
import tensorflow as tf
import numpy as np

img_path = list(uploaded.keys())[0]

img = tf.keras.preprocessing.image.load_img(
    img_path,
    target_size=(224,224)
)

img_array = tf.keras.preprocessing.image.img_to_array(img)

img_array = img_array / 255.0

img_array = np.expand_dims(img_array, axis=0)

#make prediction
prediction = model.predict(img_array)

temp_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=(224,224),
    batch_size=32,
    shuffle=False
)

class_names = temp_ds.class_names

predicted_index = np.argmax(prediction[0])

print("Predicted Tribe:", class_names[predicted_index])

confidence = np.max(prediction) * 100

print(f"Confidence: {confidence:.2f}%")
